---
title: "Formulating Political Research Questions"
format: gfm
html-math-method: webtex
---

The first step in the process of political research is formulating a 
question. For instance, scholars of political representation have long 
pondered whether the interests of privileged social groups are 
disproportionately represented in policy outcomes and why such inequalities 
arise. This week's focus will be on formulating and narrowing an empirical 
research question. We will also cover how to survey existing research on a 
subject effectively and efficiently using Google Scholar and other resources.

### Tuesday, January 24th, 2023

- Huntington-Klein, Nick. 2022. ["Research Questions"](https://theeffectbook.net/ch-ResearchQuestions.html) in *The Effect: An Introduction to Research Design and Causality*. Boca Raton, FL: CRC Press, 1--18

### Thursday, January 26th, 2023

- Huntington-Klein, Nick. 2022. ["Describing Variables"](https://theeffectbook.net/ch-DescribingVariables.html) in *The Effect: An Introduction to Research Design and Causality*. Boca Raton, FL: CRC Press, 19--43

- Lupu, Noam, and Zach Warner. 2022. "Affluence and Congruence: Unequal Representation around the World" *Journal of Politics* 84(1): 276--290. doi/dataverse: [10.1086/714930](https://doi.org/10.1086/714930); [10.7910/DVN/DBNBEU](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DBNBEU)

- Problem Set 0 is Due via Canvas by Sunday, January 29th, 2023 at 11:59 PM

### Recommended Readings

- Geddes, Barbara. 2003. *Paradigms and Sand Castles: Theory Building and Research Design in Comparative Politics*. Ann Arbor: University of Michigan Press, 27--88