---
title: "Theory Building in Political Science"
format: gfm
html-math-method: webtex
---

At the most basic level, a theory is a verbal or formal explanation 
that describes a causal relationship between two or more variables. That is, a 
theory is our proposed answer to the question of why and how some phenomena 
occurs; a data story about why we think a causal relationship such as $Race \longrightarrow Vote~Choice$ or $Federalism_{j[t]} \longrightarrow Conflict_{j[t+1]}$ exists. This week we look at what makes a good theory, different ways of 
verbally and formally expressing theoretical relationships, and making 
explicit connections between research question, theory, and data.

### Tuesday, February 7th, 2023

- Huntington-Klein, Nick. 2022. ["Causal Diagrams"](https://theeffectbook.net/ch-CausalDiagrams.html) in *The Effect: An Introduction to Research Design and Causality*. Boca Raton, FL: CRC Press, 88--100

- Barnes, Tiffany D., and Mirya R. Holman. 2020. "Gender Quotas, Women’s Representation, and Legislative Diversity." *Journal of Politics* 82(4): 1271-1286. doi/dataverse: [10.1086/708336](https://doi.org/10.1086/708336); [10.7910/DVN/9TFMSG](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/9TFMSG)

### Thursday, February 9th, 2023

- Huntington-Klein, Nick. 2022. ["Drawing Causal Diagrams"](https://theeffectbook.net/ch-CausalPaths.html) in *The Effect: An Introduction to Research Design and Causality*. Boca Raton, FL: CRC Press, 101--116.

- Lundberg, Ian, Rebecca Johnson, and Brandon M. Stewart. 2021. "What Is Your Estimand? Defining the Target Quantity Connects Statistical Evidence to Theory." *American Sociological Review* 86(3): 532-565. doi/dataverse: [10.1177/00031224211004187](https://doi.org/10.1177/00031224211004187); [10.7910/DVN/ASGOVU](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ASGOVU)

### Recommended Readings

- Claassen, Christopher. 2020. "Does Public Support Help Democracy Survive?" *American Journal of Political Science*, 64(1): 118-134. doi/dataverse: [10.1111/ajps.12452](https://doi.org/10.1111/ajps.12452); [10.7910/DVN/HWLW0J](https://doi.org/10.7910/DVN/HWLW0J)